
apiVersion: batch/v1
kind: Job
metadata:
  name: iot-90r-10w
  labels:
    app: dsbench
    phase: main
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: dsbench
        phase: main
    spec:
      containers:
      - name: dsbench
        image: datastaxlabs/dsbench
        command:
        - dsbench run type=cql yaml=/config/iot.yaml tags=phase:main host=example-cluster-example-dc-1-service threads=200 cycles=0..1000000 dc=example-dc-1 write_cl=LOCAL_QUORUM read_cl=LOCAL_QUORUM write_ratio=9 read_ratio=1 --report-graphite-to exporter-0.graphite-metrics-exporter:9109
        resources:
          requests:
            cpu: "4"
            memory: 14Gi
        volumeMounts:
        - name: dsbench-config-volume
          mountPath: /config
      nodeSelector:
        role: stress-worker
      tolerations:
      - key: nosched
        operator: "Exists"
        effect: NoSchedule
      restartPolicy: Never
      volumes:
      - name: dsbench-config-volume
        configMap:
          name: dsbench-config
  backoffLimit: 4
