# https://kubernetes.io/docs/tasks/job/parallel-processing-expansion/#multiple-template-parameters
# 1M
apiVersion: batch/v1
kind: Job
metadata:
  name: iot-ramp
  labels:
    app: dsbench
    phase: ramp
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: dsbench
        phase: ramp
    spec:
      containers:
      - name: dsbench
        image: datastaxlabs/dsbench
        command:
        - dsbench run type=cql yaml=/config/iot.yaml tags=phase:rampup host=example-cluster-example-dc-1-service threads=512 stride=10000 cyclerate=175000 async=5120 cycles=0..1000000 dc=example-dc-1 write_cl=LOCAL_ONE read_cl=LOCAL_ONE --report-graphite-to exporter-0.graphite-metrics-exporter:9109
        resources:
          requests:
            cpu: "4"
            memory: 14Gi
        volumeMounts:
        - name: dsbench-config-volume
          mountPath: /config
      nodeSelector:
        role: stress-worker
      tolerations:
      - key: nosched
        operator: "Exists"
        effect: NoSchedule
      restartPolicy: Never
      volumes:
      - name: dsbench-config-volume
        configMap:
          name: dsbench-config
  backoffLimit: 4
