apiVersion: batch/v1
kind: Job
metadata:
  name: iot-schema
  labels:
    app: dsbench
    phase: schema
spec:
  completions: 1
  template:
    spec:
      containers:
      - name: dsbench
        image: datastaxlabs/dsbench
        command:
        - dsbench run type=cql yaml=/config/iot.yaml tags=phase:schema host=example-cluster-example-dc-1-service cycles=3 rf=3 dc=example-dc-1 --report-graphite-to exporter-0.graphite-metrics-exporter:9109
        resources:
          requests:
            cpu: 4
            memory: 32Gi
        volumeMounts:
        - name: dsbench-config-volume
          mountPath: /config
      nodeSelector:
        role: stress-worker
      tolerations:
      - key: nosched
        operator: "Exists"
        effect: NoSchedule
      restartPolicy: Never
      volumes:
      - name: dsbench-config-volume
        configMap:
          name: dsbench-config
  backoffLimit: 4
