kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  apiServerPort: 45451
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 3000
    hostPort: 3000
    listenAddress: "0.0.0.0"
